### ISSUE TITLE
Version dependant crash example inputs

### ISSUE THREAD

**Issue by MarkTreeSMS** [Admiral-Fish/JirachiAdvancer#3]
Crash with no output provided running what I believe may be an older version. According to xdseed, the below should represent a target frame which is 84 frames away.

Using version [JirachiAdvancer_1.exe].
Inputs:
Current seed: 0xAA2DA755
Target seed: 0x7BE695B9

Alternative version [JirachiAdvancer (2).exe] (from Dropbox link) works, providing four steps including "Exit Special Cutscene".

Thanks

**Comment by Admiral-Fish** [comment]
Latest commit shows this current and target as being unreachable. This is the intended behavior
